version: "3.9"

services:
  google-books:
    container_name: google-books-c
    image: google-books-i
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:3000"
    command: npm run dev
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped